#[allow(
    unused,
    reason = "false positive (also 'expect' doesn't seem to work so we use 'allow'"
)]
pub use self::{mods::*, paths::*};

/// Paths to .osu files
mod paths {
    pub const OSU: &str = "./resources/2785319.osu";
    pub const TAIKO: &str = "./resources/1028484.osu";
    pub const CATCH: &str = "./resources/2118524.osu";
    pub const MANIA: &str = "./resources/1638954.osu";
}

/// Bit values for mods
mod mods {
    #![allow(
        unused,
        reason = "false positive (also 'expect' doesn't seem to work so we use 'allow'"
    )]

    pub const NM: u32 = 0;
    pub const NF: u32 = 1 << 0;
    pub const EZ: u32 = 1 << 1;
    pub const TD: u32 = 1 << 2;
    pub const HD: u32 = 1 << 3;
    pub const HR: u32 = 1 << 4;
    pub const DT: u32 = 1 << 6;
    pub const HT: u32 = 1 << 8;
    pub const FL: u32 = 1 << 10;
    pub const SO: u32 = 1 << 12;
}

/// How many ULPs of slack [`assert_eq_float`] allows.
///
/// The float comparisons in these tests are a regression signal, not a
/// bit-equality gate. `f64::EPSILON` used as an *absolute* tolerance is not a
/// tolerance at all for values far from `1.0`: one ULP of `468.2` is about
/// `2.6e4 * f64::EPSILON`, so an absolute comparison silently demands
/// bit-identical output and turns every literal into a libm- and
/// platform-specific value.
///
/// That is exactly what made `tests/performance.rs::basic_osu` fail: its
/// `pp_reading` and `pp` literals were generated by an earlier revision of the
/// osu!standard reading implementation and differ from the current output by a
/// single ULP (verified against the pinned 5.0.2 reference, which produces the
/// same bits as this revision).
///
/// Scaling the machine epsilon by the operands' magnitude - with a floor of
/// `1.0`, so the comparison stays tight near zero - gives the usual relative
/// comparison while still failing anything off by more than a handful of ULPs.
/// Bit-exactness is guarded separately and strictly: `scripts/verify.ps1` diffs
/// a 133-row matrix to ten decimal places, and `osu-pp-bench --example ref_diff`
/// diffs the full map x mode x mod matrix bit-for-bit against the pinned 5.0.2
/// reference.
const ULP_SLACK: u32 = 8;

#[track_caller]
pub fn assert_eq_float<F: Float>(a: F, b: F) {
    assert!(a.almost_eq(b), "{a} != {b}")
}

#[track_caller]
#[allow(
    unused,
    reason = "false positive (also 'expect' doesn't seem to work so we use 'allow'"
)]
pub fn assert_eq_option<F: Float>(a: Option<F>, b: Option<F>) {
    match (a, b) {
        (Some(a), Some(b)) => assert!(a.almost_eq(b), "{a} != {b}"),
        (None, None) => {}
        (None, Some(b)) => panic!("None != Some({b})"),
        (Some(a), None) => panic!("Some({a}) != None"),
    }
}

/// Trait to provide flexibility in the `assert_eq_float` function.
pub trait Float:
    Copy
    + std::fmt::Display
    + std::ops::Sub<Output = Self>
    + std::ops::Mul<Output = Self>
    + PartialOrd
    + Sized
{
    /// The relative tolerance actually applied: the machine epsilon times
    /// [`ULP_SLACK`].
    const SLACK: Self;

    const ONE: Self;

    fn abs(self) -> Self;

    fn max(self, other: Self) -> Self;

    /// `self` and `other` agree to within [`ULP_SLACK`] ULPs of their magnitude,
    /// with a floor of `1.0` so the check stays tight near zero.
    fn almost_eq(self, other: Self) -> bool {
        let diff = (self - other).abs();
        let scale = self.abs().max(other.abs()).max(Self::ONE);

        diff <= Self::SLACK * scale
    }
}

macro_rules! impl_float {
    ( $( $ty:ty )* ) => {
        $(
            impl Float for $ty {
                const SLACK: Self = <$ty>::EPSILON * ULP_SLACK as $ty;
                const ONE: Self = 1.0;

                fn abs(self) -> Self {
                    self.abs()
                }

                fn max(self, other: Self) -> Self {
                    <$ty>::max(self, other)
                }
            }
        )*
    }
}

impl_float!(f32 f64);

/// Trait to compare two instances and panic if they are not equal.
#[allow(
    unused,
    reason = "false positive (also 'expect' doesn't seem to work so we use 'allow'"
)]
pub trait AssertEq {
    fn assert_eq(&self, expected: &Self);
}
